runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

env_variables:
  SQLALCHEMY_DATABASE_URI: >-
    mysql+pymysql://root:pgriffith_cloud_learningassword@/currencies?unix_socket=/cloudsql/lexical-archery-231806:australia-southeast1:googlecloudsql

beta_settings:
  cloud_sql_instances: australia-southeast1:googlecloudsql