runtime: python
api_version: 1
threadsafe: true
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
runtime_config:
    python_version: 3
    
libraries:
  - name: ssl
    version: latest
